// <auto-generated />
using System;
using LineNotify.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LineNotify.Api.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LineNotify.Api.Models.Admin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSuperAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("LinkedUserId")
                        .HasColumnType("int");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("LinkedUserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Admins");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(4400),
                            DisplayName = "系統管理員",
                            IsActive = true,
                            IsSuperAdmin = true,
                            MustChangePassword = true,
                            PasswordHash = "$2a$11$K3LiTXHXrCXl7J5GQs0B6eFg2y1YuP1W5m2X3Qk4R5v6N7M8O9P0Q",
                            UpdatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(4400),
                            Username = "ADMIN"
                        });
                });

            modelBuilder.Entity("LineNotify.Api.Models.ApiKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByAdminId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("ExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("KeyHash")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("KeyPrefix")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("LastUsedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Permissions")
                        .HasColumnType("json");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<long>("UsageCount")
                        .HasColumnType("bigint");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByAdminId");

                    b.HasIndex("KeyHash")
                        .IsUnique();

                    b.HasIndex("KeyPrefix");

                    b.HasIndex("UserId");

                    b.ToTable("ApiKeys");
                });

            modelBuilder.Entity("LineNotify.Api.Models.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NewValues")
                        .HasColumnType("longtext");

                    b.Property<string>("OldValues")
                        .HasColumnType("longtext");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("LineNotify.Api.Models.Group", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowDuplicateAlerts")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("DuplicateAlertIntervalMinutes")
                        .HasColumnType("int");

                    b.Property<string>("HostFilter")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("MuteTimeEnd")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("MuteTimeStart")
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ReceiveTimeEnd")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ReceiveTimeStart")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<string>("ServiceFilter")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Groups");
                });

            modelBuilder.Entity("LineNotify.Api.Models.GroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AddedByAdminId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddedByAdminId");

                    b.HasIndex("UserId");

                    b.HasIndex("GroupId", "UserId")
                        .IsUnique();

                    b.ToTable("GroupMembers");
                });

            modelBuilder.Entity("LineNotify.Api.Models.GroupMessageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int>("MessageTypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MessageTypeId");

                    b.HasIndex("GroupId", "MessageTypeId")
                        .IsUnique();

                    b.ToTable("GroupMessageTypes");
                });

            modelBuilder.Entity("LineNotify.Api.Models.LoginLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AdminId")
                        .HasColumnType("int");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsSuccess")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LoginType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("UserAgent")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.HasIndex("LoginAt");

                    b.HasIndex("UserId", "LoginAt");

                    b.ToTable("LoginLogs");
                });

            modelBuilder.Entity("LineNotify.Api.Models.Message", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("ApiKeyId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("MessageTypeId")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .HasColumnType("json");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("ProcessedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SourceHost")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("SourceIp")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SourceService")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<string>("TargetGroups")
                        .HasColumnType("json");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("ApiKeyId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("MessageTypeId");

                    b.HasIndex("SourceHost", "SourceService", "MessageTypeId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("LineNotify.Api.Models.MessageDelivery", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("LineMessageId")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("MessageId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NextRetryAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ScheduledAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("SentAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NextRetryAt");

                    b.HasIndex("Status");

                    b.HasIndex("UserId");

                    b.HasIndex("MessageId", "UserId")
                        .IsUnique();

                    b.ToTable("MessageDeliveries");
                });

            modelBuilder.Entity("LineNotify.Api.Models.MessageType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("varchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Icon")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsSystemDefault")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("MessageTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Code = "CRITICAL",
                            Color = "#FF0000",
                            CreatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(310),
                            Description = "嚴重告警，需要立即處理",
                            Icon = "🔴",
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "嚴重",
                            Priority = 1,
                            UpdatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(310)
                        },
                        new
                        {
                            Id = 2,
                            Code = "WARNING",
                            Color = "#FFA500",
                            CreatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(1500),
                            Description = "警告告警，需要關注",
                            Icon = "🟠",
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "警告",
                            Priority = 2,
                            UpdatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(1500)
                        },
                        new
                        {
                            Id = 3,
                            Code = "UNKNOWN",
                            Color = "#808080",
                            CreatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(1510),
                            Description = "未知狀態",
                            Icon = "⚪",
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "未知",
                            Priority = 3,
                            UpdatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(1510)
                        },
                        new
                        {
                            Id = 4,
                            Code = "OK",
                            Color = "#00FF00",
                            CreatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(1510),
                            Description = "恢復正常",
                            Icon = "🟢",
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "正常",
                            Priority = 4,
                            UpdatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(1510)
                        },
                        new
                        {
                            Id = 5,
                            Code = "INFO",
                            Color = "#0000FF",
                            CreatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(1510),
                            Description = "一般資訊通知",
                            Icon = "🔵",
                            IsActive = true,
                            IsSystemDefault = true,
                            Name = "資訊",
                            Priority = 5,
                            UpdatedAt = new DateTime(2025, 12, 31, 12, 59, 53, 572, DateTimeKind.Utc).AddTicks(1510)
                        });
                });

            modelBuilder.Entity("LineNotify.Api.Models.Subscription", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("MessageTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("MessageTypeId");

                    b.HasIndex("UserId", "MessageTypeId", "GroupId")
                        .IsUnique();

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("LineNotify.Api.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("varchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LineAccessToken")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("LineAccessTokenExpiresAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LineUserId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("PictureUrl")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("Email");

                    b.HasIndex("LineUserId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("LineNotify.Api.Models.Admin", b =>
                {
                    b.HasOne("LineNotify.Api.Models.User", "LinkedUser")
                        .WithMany()
                        .HasForeignKey("LinkedUserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("LinkedUser");
                });

            modelBuilder.Entity("LineNotify.Api.Models.ApiKey", b =>
                {
                    b.HasOne("LineNotify.Api.Models.Admin", "CreatedByAdmin")
                        .WithMany()
                        .HasForeignKey("CreatedByAdminId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNotify.Api.Models.User", null)
                        .WithMany("ApiKeys")
                        .HasForeignKey("UserId");

                    b.Navigation("CreatedByAdmin");
                });

            modelBuilder.Entity("LineNotify.Api.Models.AuditLog", b =>
                {
                    b.HasOne("LineNotify.Api.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("LineNotify.Api.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LineNotify.Api.Models.GroupMember", b =>
                {
                    b.HasOne("LineNotify.Api.Models.Admin", "AddedByAdmin")
                        .WithMany()
                        .HasForeignKey("AddedByAdminId");

                    b.HasOne("LineNotify.Api.Models.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNotify.Api.Models.User", "User")
                        .WithMany("GroupMemberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AddedByAdmin");

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LineNotify.Api.Models.GroupMessageType", b =>
                {
                    b.HasOne("LineNotify.Api.Models.Group", "Group")
                        .WithMany("MessageTypes")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNotify.Api.Models.MessageType", "MessageType")
                        .WithMany("GroupMessageTypes")
                        .HasForeignKey("MessageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MessageType");
                });

            modelBuilder.Entity("LineNotify.Api.Models.LoginLog", b =>
                {
                    b.HasOne("LineNotify.Api.Models.Admin", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.HasOne("LineNotify.Api.Models.User", "User")
                        .WithMany("LoginLogs")
                        .HasForeignKey("UserId");

                    b.Navigation("Admin");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LineNotify.Api.Models.Message", b =>
                {
                    b.HasOne("LineNotify.Api.Models.ApiKey", "ApiKey")
                        .WithMany("Messages")
                        .HasForeignKey("ApiKeyId");

                    b.HasOne("LineNotify.Api.Models.MessageType", "MessageType")
                        .WithMany("Messages")
                        .HasForeignKey("MessageTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ApiKey");

                    b.Navigation("MessageType");
                });

            modelBuilder.Entity("LineNotify.Api.Models.MessageDelivery", b =>
                {
                    b.HasOne("LineNotify.Api.Models.Message", "Message")
                        .WithMany("Deliveries")
                        .HasForeignKey("MessageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNotify.Api.Models.User", "User")
                        .WithMany("MessageDeliveries")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Message");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LineNotify.Api.Models.Subscription", b =>
                {
                    b.HasOne("LineNotify.Api.Models.Group", "Group")
                        .WithMany("Subscriptions")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNotify.Api.Models.MessageType", "MessageType")
                        .WithMany("Subscriptions")
                        .HasForeignKey("MessageTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LineNotify.Api.Models.User", "User")
                        .WithMany("Subscriptions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("MessageType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LineNotify.Api.Models.ApiKey", b =>
                {
                    b.Navigation("Messages");
                });

            modelBuilder.Entity("LineNotify.Api.Models.Group", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("MessageTypes");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("LineNotify.Api.Models.Message", b =>
                {
                    b.Navigation("Deliveries");
                });

            modelBuilder.Entity("LineNotify.Api.Models.MessageType", b =>
                {
                    b.Navigation("GroupMessageTypes");

                    b.Navigation("Messages");

                    b.Navigation("Subscriptions");
                });

            modelBuilder.Entity("LineNotify.Api.Models.User", b =>
                {
                    b.Navigation("ApiKeys");

                    b.Navigation("GroupMemberships");

                    b.Navigation("LoginLogs");

                    b.Navigation("MessageDeliveries");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
